// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9dZ3ahECKV1SuVTbhmW0GeplBW_GdJo',
    appId: '1:687010429513:web:b765e83a03b817423c1d98',
    messagingSenderId: '687010429513',
    projectId: 'bilgi-rotasi',
    authDomain: 'bilgi-rotasi.firebaseapp.com',
    storageBucket: 'bilgi-rotasi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBsYV2alw5ZHI8tMGzeW4WdhrDcFndaN4',
    appId: '1:687010429513:android:9674807cf1c40d173c1d98',
    messagingSenderId: '687010429513',
    projectId: 'bilgi-rotasi',
    storageBucket: 'bilgi-rotasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXagmDa7kEfUrLIWqM8yInltUK1VWLhx8',
    appId: '1:687010429513:ios:d0c0fb8441d081f83c1d98',
    messagingSenderId: '687010429513',
    projectId: 'bilgi-rotasi',
    storageBucket: 'bilgi-rotasi.firebasestorage.app',
    iosBundleId: 'com.example.sinavLigiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXagmDa7kEfUrLIWqM8yInltUK1VWLhx8',
    appId: '1:687010429513:ios:d0c0fb8441d081f83c1d98',
    messagingSenderId: '687010429513',
    projectId: 'bilgi-rotasi',
    storageBucket: 'bilgi-rotasi.firebasestorage.app',
    iosBundleId: 'com.example.sinavLigiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9dZ3ahECKV1SuVTbhmW0GeplBW_GdJo',
    appId: '1:687010429513:web:6cce23f2f6a8b78a3c1d98',
    messagingSenderId: '687010429513',
    projectId: 'bilgi-rotasi',
    authDomain: 'bilgi-rotasi.firebaseapp.com',
    storageBucket: 'bilgi-rotasi.firebasestorage.app',
  );
}
